sudo: false
os: linux
language: d
d: dmd-2.071.0
install:
 - wget "https://raw.githubusercontent.com/dlang/dmd/master/src/checkwhitespace.d" -O ../checkwhitespace.d
 - git clone https://github.com/Hackerpilot/Dscanner
 - (cd Dscanner && git checkout tags/v0.4.0-alpha4)
 - (cd Dscanner && git submodule update --init --recursive)
 # debug build is faster, but disable 'missing import' messages (missing core from druntime)
 - (cd Dscanner && sed 's/dparse_verbose/StdLoggerDisableWarning/' -i makefile && make githash debug)
 # avoid checking it's dscanner's directory
 - mv Dscanner/dsc .
 - rm -rf Dscanner
script:
 - (cd .. && rdmd ./checkwhitespace.d $(find phobos -name '*.d'))
 # enforce whitespace between statements
 - grep -E "(for|foreach|foreach_reverse|if|while)\(" $(find . -name '*.d'); test $? -eq 1
 # at the moment libdparse has problems to parse some modules (->excludes)
 - ./dsc --config .dscanner.ini --styleCheck $(find etc std -type f -name '*.d' | grep -vE 'std/traits.d|std/typecons.d|std/conv.d') -I.
