sudo: false
os: linux
language: d
d: dmd-2.071.0
install:
 - wget "https://raw.githubusercontent.com/dlang/dmd/master/src/checkwhitespace.d" -O ../checkwhitespace.d
 - git clone https://github.com/Hackerpilot/Dscanner
 - (cd Dscanner && git checkout tags/v0.4.0-alpha2)
 - (cd Dscanner && git submodule update --init --recursive)
 - (cd Dscanner && make githash debug)
 - mv Dscanner/dsc .
 - rm -rf Dscanner
script:
 - (cd .. && rdmd ./checkwhitespace.d $(find phobos -name '*.d'))
 - grep -E "(for|foreach|foreach_reverse|if|while)\(" $(find . -name '*.d'); test $? -eq 1
 - dscanResult=$(./dscanner --config .dscanner.ini --styleCheck std etc 2> /dev/null | grep -vE "(Empty declaration|Primary expression expected)") ; if [ -z "${dscanResult}" ] ; then echo "No warnings found" ; else echo $dscanResult && $(exit 1); fi
